### ISSUE TITLE
Incorrect body types

### ISSUE THREAD

**Issue by Furion001** [EvilDraggie/YingWorld#23]
![image](https://user-images.githubusercontent.com/7419121/113349449-4c51bc80-92f5-11eb-9a38-3853015fb715.png)
Yinglets get female body type regardless of gender

**Comment by Avris** [comment]
Are you using the current version? 

We haven't had pawn drawsize matching your screenshot since last year, and there was briefly a bug at the time with younglets getting incorrect bodytypes when they grew up. That's been fixed for almost five months. Please update and verify that Stimp still has the wrong body.
